package fr.unice.polytech.qgl.qdd.enums;

import java.util.ArrayList;

public enum BiomeEnum {

	ALPINE,
	BEACH,
	GLACIER,
	GRASSLAND,
	MANGROVE,
	OCEAN,
	SHRUBLAND,
	SNOW,
	SUB_TROPICAL_DESERT,
	TAIGA,
	TEMPERATE_DECIDUOUS_FOREST,
	TEMPERATE_DESERT,
	TEMPERATE_RAIN_FOREST,
	TROPICAL_RAIN_FOREST,
	TROPICAL_SEASONAL_FOREST,
	TUNDRA;
}
